Adding couple shapes + validation messages
andyghiuta/js-training-advanced pull request #2
Opened 2018-07-28 12:03 UTC by novokaine

Added shapes, relatively easy using prototype
Added validation messages - struggled a log with them, not fully satisfied with the final result but it's a working copy.

2018-07-30 17:36 UTC, andyghiuta commented on public/src/validation.js
> +  shapeAttr.push(x);
`this.x` maybe?

2018-07-30 17:56 UTC, andyghiuta requested changes
I will create a different branch: "solutions" and please make the pull request there.

2018-07-30 17:56 UTC, andyghiuta commented on public/src/drawing.js
> +  if(shapeValidation.validateShape(shapeProps)){
Since `validateShape` is added on the `Shape` prototype and all other shapes extends `Shape`, they all have the method. Try: `shape.validateShape()` after the shape is created.
Additionally, shapes could overwrite the validateShape (see `drawFrame`) for grannular vlidations. Now you support basically only two validations, but different shapes may require different validations. Eg: arc angles can be between 0 and 360 degrees.

2018-07-30 17:56 UTC, andyghiuta commented on public/src/drawing.js
> +  ctx.arc(this.x, this.y, this.angleStart, this.angleEnd, this.radius * Math.PI);
`angleStart` and `angleEnd` are probably best specified in degrees and converted here to radians (function arc accepts radians. 1 rad = 180 / PI degrees).

2018-07-30 17:56 UTC, andyghiuta commented on public/src/drawing.js
> +Shape.prototype.appendErrorMsg = function validateShape(){
inconsistency in function naming

2018-07-30 17:56 UTC, andyghiuta commented on public/src/drawing.js
> +function Ark(x, y, angleStart, angleEnd,  radius){
`Arc` is probably a better name than `Ark` (Noah's Ark? 😛)

2018-07-30 17:56 UTC, andyghiuta commented on public/src/validation.js
> +showError.prototype.appendErrorMsg = function appendErrorMsg(message, appendTo) {
`appendErrorMsg` and `removeErrorMsg` don't need to be on the object. They can be defined globally since they don't depend on any shape methods or properties as far as I can tell and use only the provided params.

2018-07-30 18:00 UTC, closed without merging

2018-07-31 06:00 UTC, novokaine commented on public/src/validation.js
> +  shapeAttr.push(x);
Kida disagree, this.x is undefined. x instead is giving me the input field

2018-07-31 06:02 UTC, novokaine commented on public/src/drawing.js
> +function Ark(x, y, angleStart, angleEnd,  radius){
Fixed